server:
  port: 9090

spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:1111


management:
  endpoints:
    web:
      exposure:
        include: "*" # Spring boot actuator端点启用和暴露