server:
  port: 9090

spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:1111


management:
  endpoints:
    web:
      exposure:
        include: "*" # Spring boot actuator端点启用和暴露

seata:
  enabled: true
  application-id: bl-blog-global
  tx-service-group: lionet_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace: "e651af00-158b-4105-a8fc-818b577c6daa"
      serverAddr: http://localhost:1111
      group: SEATA_GROUP
      userName: "lionet"
      password: "123456"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: http://localhost:1111
      namespace: "e651af00-158b-4105-a8fc-818b577c6daa"
      userName: "lionet"
      password: "123456"