server:
  port: 9999
spring:
  application:
    name:bl-blog-manage-view
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:1111


management:
  endpoints:
    web:
      exposure:
        include: "*" # Spring boot actuator端点启用和暴露