server:
  port: 9091
spring:
  application:
    name: bl-blog-gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:1111
   # gateway:
   #   routes:
        #路由的ID，没有固定规则但要求唯一，建议配合服务名
   #     - id: payment_routh
          #匹配后提供服务的路由地址
   #       uri: "lb://bl-blog-dispatch"
   #       predicates:
            #断言,路径相匹配的进行路由
   #         - Path= /**
management:
  endpoints:
    web:
      exposure:
        include: "*" # Spring boot actuator端点启用和暴露