server:
  port: 9091
spring:
  application:
    name: bl-blog-gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:1111



management:
  endpoints:
    web:
      exposure:
        include: "*" # Spring boot actuator端点启用和暴露
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED


  skip-auth-urls