server:
  port: 9094
spring:
  application:
    name: bl-blog-template
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:1111

management:
  endpoints:
    web:
      exposure:
        include: "*" # Spring boot actuator端点启用和暴露